//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.DataProducer.ServiceImplement.TraceLogCenter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceLogInfo", Namespace="http://schemas.datacontract.org/2004/07/MDT.ManageCenter.DataContract")]
    [System.SerializableAttribute()]
    public partial class TraceLogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceStage StageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubTaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataCount {
            get {
                return this.DataCountField;
            }
            set {
                if ((this.DataCountField.Equals(value) != true)) {
                    this.DataCountField = value;
                    this.RaisePropertyChanged("DataCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RunInfo {
            get {
                return this.RunInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RunInfoField, value) != true)) {
                    this.RunInfoField = value;
                    this.RaisePropertyChanged("RunInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceStage Stage {
            get {
                return this.StageField;
            }
            set {
                if ((this.StageField.Equals(value) != true)) {
                    this.StageField = value;
                    this.RaisePropertyChanged("Stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubTaskId {
            get {
                return this.SubTaskIdField;
            }
            set {
                if ((this.SubTaskIdField.Equals(value) != true)) {
                    this.SubTaskIdField = value;
                    this.RaisePropertyChanged("SubTaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceStage", Namespace="http://schemas.datacontract.org/2004/07/MDT.ManageCenter.DataContract")]
    public enum TraceStage : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataProducer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataConsumer = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceStatus", Namespace="http://schemas.datacontract.org/2004/07/MDT.ManageCenter.DataContract")]
    public enum TraceStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Handle = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TraceLogCenter.ITraceLogCenterService")]
    public interface ITraceLogCenterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraceLogCenterService/Write", ReplyAction="http://tempuri.org/ITraceLogCenterService/WriteResponse")]
        void Write(MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceLogInfo traceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraceLogCenterService/Read", ReplyAction="http://tempuri.org/ITraceLogCenterService/ReadResponse")]
        MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceLogInfo Read(int traceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITraceLogCenterServiceChannel : MDT.DataProducer.ServiceImplement.TraceLogCenter.ITraceLogCenterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TraceLogCenterServiceClient : System.ServiceModel.ClientBase<MDT.DataProducer.ServiceImplement.TraceLogCenter.ITraceLogCenterService>, MDT.DataProducer.ServiceImplement.TraceLogCenter.ITraceLogCenterService {
        
        public TraceLogCenterServiceClient() {
        }
        
        public TraceLogCenterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraceLogCenterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraceLogCenterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraceLogCenterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Write(MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceLogInfo traceInfo) {
            base.Channel.Write(traceInfo);
        }
        
        public MDT.DataProducer.ServiceImplement.TraceLogCenter.TraceLogInfo Read(int traceId) {
            return base.Channel.Read(traceId);
        }
    }
}
