//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.DataProducer.ServiceImplement.EmailCenter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailCenter.IEmailCenterService")]
    public interface IEmailCenterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailCenterService/Send", ReplyAction="http://tempuri.org/IEmailCenterService/SendResponse")]
        void Send(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailCenterService/NoticeService", ReplyAction="http://tempuri.org/IEmailCenterService/NoticeServiceResponse")]
        void NoticeService(string account, string message, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailCenterService/ActiveNoticeService", ReplyAction="http://tempuri.org/IEmailCenterService/ActiveNoticeServiceResponse")]
        void ActiveNoticeService(int taskid, string Message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailCenterServiceChannel : MDT.DataProducer.ServiceImplement.EmailCenter.IEmailCenterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailCenterServiceClient : System.ServiceModel.ClientBase<MDT.DataProducer.ServiceImplement.EmailCenter.IEmailCenterService>, MDT.DataProducer.ServiceImplement.EmailCenter.IEmailCenterService {
        
        public EmailCenterServiceClient() {
        }
        
        public EmailCenterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailCenterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailCenterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailCenterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(string message) {
            base.Channel.Send(message);
        }
        
        public void NoticeService(string account, string message, int type) {
            base.Channel.NoticeService(account, message, type);
        }
        
        public void ActiveNoticeService(int taskid, string Message) {
            base.Channel.ActiveNoticeService(taskid, Message);
        }
    }
}
