//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.DataProducer.ServiceImplement.DataConsumer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataConsumer.IDataConsumerService")]
    public interface IDataConsumerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataConsumerService/Send", ReplyAction="http://tempuri.org/IDataConsumerService/SendResponse")]
        void Send(int taskId, string processLN, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataConsumerService/ReSend", ReplyAction="http://tempuri.org/IDataConsumerService/ReSendResponse")]
        void ReSend(int traceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataConsumerServiceChannel : MDT.DataProducer.ServiceImplement.DataConsumer.IDataConsumerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataConsumerServiceClient : System.ServiceModel.ClientBase<MDT.DataProducer.ServiceImplement.DataConsumer.IDataConsumerService>, MDT.DataProducer.ServiceImplement.DataConsumer.IDataConsumerService {
        
        public DataConsumerServiceClient() {
        }
        
        public DataConsumerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataConsumerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataConsumerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataConsumerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(int taskId, string processLN, string data) {
            base.Channel.Send(taskId, processLN, data);
        }
        
        public void ReSend(int traceId) {
            base.Channel.ReSend(traceId);
        }
    }
}
