//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.WebUI.DataTransform {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataTransform.IDataTransformService")]
    public interface IDataTransformService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransformService/Send", ReplyAction="http://tempuri.org/IDataTransformService/SendResponse")]
        void Send(string xmlData, int taskid, string processLN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataTransformService/ReSend", ReplyAction="http://tempuri.org/IDataTransformService/ReSendResponse")]
        void ReSend(int traceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataTransformServiceChannel : MDT.WebUI.DataTransform.IDataTransformService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataTransformServiceClient : System.ServiceModel.ClientBase<MDT.WebUI.DataTransform.IDataTransformService>, MDT.WebUI.DataTransform.IDataTransformService {
        
        public DataTransformServiceClient() {
        }
        
        public DataTransformServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataTransformServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransformServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransformServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(string xmlData, int taskid, string processLN) {
            base.Channel.Send(xmlData, taskid, processLN);
        }
        
        public void ReSend(int traceId) {
            base.Channel.ReSend(traceId);
        }
    }
}
